name: unit tests

on:
  push:
  schedule:
    - cron: "0 21 * * 6"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt
          python -m pip install git+https://github.com/speedcell4/torchrua.git@develop --force-reinstall --no-deps
          python -m pip install pytest hypothesis torchnyan
          python -m pip install pytorch-crf torch-struct
      - name: Test with pytest
        run: |
          python -m pytest tests